"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MocTC__factory = exports.MocRC20__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MocRC20__factory_1 = require("./MocRC20__factory");
Object.defineProperty(exports, "MocRC20__factory", { enumerable: true, get: function () { return MocRC20__factory_1.MocRC20__factory; } });
var MocTC__factory_1 = require("./MocTC__factory");
Object.defineProperty(exports, "MocTC__factory", { enumerable: true, get: function () { return MocTC__factory_1.MocTC__factory; } });
//# sourceMappingURL=index.js.map