"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MocCACoinbase__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MocCACoinbase__factory_1 = require("./MocCACoinbase__factory");
Object.defineProperty(exports, "MocCACoinbase__factory", { enumerable: true, get: function () { return MocCACoinbase__factory_1.MocCACoinbase__factory; } });
//# sourceMappingURL=index.js.map