"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EchidnaMocWrapperTester__factory = exports.EchidnaMocCoreTester__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var EchidnaMocCoreTester__factory_1 = require("./EchidnaMocCoreTester__factory");
Object.defineProperty(exports, "EchidnaMocCoreTester__factory", { enumerable: true, get: function () { return EchidnaMocCoreTester__factory_1.EchidnaMocCoreTester__factory; } });
var EchidnaMocWrapperTester__factory_1 = require("./EchidnaMocWrapperTester__factory");
Object.defineProperty(exports, "EchidnaMocWrapperTester__factory", { enumerable: true, get: function () { return EchidnaMocWrapperTester__factory_1.EchidnaMocWrapperTester__factory; } });
//# sourceMappingURL=index.js.map