"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Test__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ethers_1 = require("ethers");
var _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        name: "Flag",
        type: "event",
    },
    {
        inputs: [],
        name: "echidna_alwaystrue",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "echidna_revert_always",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "echidna_sometimesfalse",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "int256",
                name: "val",
                type: "int256",
            },
        ],
        name: "set0",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "int256",
                name: "val",
                type: "int256",
            },
        ],
        name: "set1",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var _bytecode = "0x60806040526000805461ffff191661010117905534801561001f57600080fd5b506102008061002f6000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806337841d371461005c5780635fcf9fce14610078578063d90babde1461007f578063e48f28d214610092578063e7c0d70c146100a5575b600080fd5b6100646100ad565b604051901515815260200160405180910390f35b6001610064565b61006461008d36600461018f565b610139565b6100646100a036600461018f565b61015d565b610064600080fd5b6000805460405160ff909116151581527fe145e7af4325483bf4c6332638929bf553f2f21bac737ea4d5b88d8a903368889060200160405180910390a160005460405161010090910460ff16151581527fe145e7af4325483bf4c6332638929bf553f2f21bac737ea4d5b88d8a903368889060200160405180910390a150600054610100900460ff1690565b60006101466064836101a8565b600003610158576000805460ff191690555b919050565b600061016a600a836101a8565b15801561017a575060005460ff16155b15610158576000805461ff0019169055919050565b6000602082840312156101a157600080fd5b5035919050565b6000826101c557634e487b7160e01b600052601260045260246000fd5b50079056fea2646970667358221220d33db11581624a6958d470e813b3ddc337da9a584b84ca773b122707d8c7500864736f6c63430008110033";
var isSuperArgs = function (xs) { return xs.length > 1; };
var Test__factory = /** @class */ (function (_super) {
    __extends(Test__factory, _super);
    function Test__factory() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        var _this = this;
        if (isSuperArgs(args)) {
            _this = _super.apply(this, args) || this;
        }
        else {
            _this = _super.call(this, _abi, _bytecode, args[0]) || this;
        }
        return _this;
    }
    Test__factory.prototype.deploy = function (overrides) {
        return _super.prototype.deploy.call(this, overrides || {});
    };
    Test__factory.prototype.getDeployTransaction = function (overrides) {
        return _super.prototype.getDeployTransaction.call(this, overrides || {});
    };
    Test__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    Test__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    Test__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Test__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Test__factory.bytecode = _bytecode;
    Test__factory.abi = _abi;
    return Test__factory;
}(ethers_1.ContractFactory));
exports.Test__factory = Test__factory;
//# sourceMappingURL=Test__factory.js.map