extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
plugins:
  - "@typescript-eslint"
env:
  node: true
  mocha: true
root: true
rules:
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: _
      varsIgnorePattern: _
