"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.NonPayableMock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "dest_",
                type: "address",
            },
            {
                internalType: "bytes",
                name: "data_",
                type: "bytes",
            },
        ],
        name: "forward",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
];
var _bytecode = "0x608060405234801561001057600080fd5b50610189806100206000396000f3fe60806040526004361061001e5760003560e01c80636fadcf7214610023575b600080fd5b6100366100313660046100b2565b610038565b005b600080846001600160a01b0316348585604051610056929190610143565b60006040518083038185875af1925050503d8060008114610093576040519150601f19603f3d011682016040523d82523d6000602084013e610098565b606091505b5091509150816100ab5780518082602001fd5b5050505050565b6000806000604084860312156100c757600080fd5b83356001600160a01b03811681146100de57600080fd5b9250602084013567ffffffffffffffff808211156100fb57600080fd5b818601915086601f83011261010f57600080fd5b81358181111561011e57600080fd5b87602082850101111561013057600080fd5b6020830194508093505050509250925092565b818382376000910190815291905056fea2646970667358221220be240cb7631997288ad6eb2e2652eda9503888dc4d727cf7c78eae0376f9b8e264736f6c63430008110033";
var isSuperArgs = function (xs) { return xs.length > 1; };
var NonPayableMock__factory = /** @class */ (function (_super) {
    __extends(NonPayableMock__factory, _super);
    function NonPayableMock__factory() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        var _this = this;
        if (isSuperArgs(args)) {
            _this = _super.apply(this, args) || this;
        }
        else {
            _this = _super.call(this, _abi, _bytecode, args[0]) || this;
        }
        return _this;
    }
    NonPayableMock__factory.prototype.deploy = function (overrides) {
        return _super.prototype.deploy.call(this, overrides || {});
    };
    NonPayableMock__factory.prototype.getDeployTransaction = function (overrides) {
        return _super.prototype.getDeployTransaction.call(this, overrides || {});
    };
    NonPayableMock__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    NonPayableMock__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    NonPayableMock__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    NonPayableMock__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    NonPayableMock__factory.bytecode = _bytecode;
    NonPayableMock__factory.abi = _abi;
    return NonPayableMock__factory;
}(ethers_1.ContractFactory));
exports.NonPayableMock__factory = NonPayableMock__factory;
//# sourceMappingURL=NonPayableMock__factory.js.map