"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IChangeContract__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "execute",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var IChangeContract__factory = /** @class */ (function () {
    function IChangeContract__factory() {
    }
    IChangeContract__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IChangeContract__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IChangeContract__factory.abi = _abi;
    return IChangeContract__factory;
}());
exports.IChangeContract__factory = IChangeContract__factory;
//# sourceMappingURL=IChangeContract__factory.js.map