"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IGovernor__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "contract IChangeContract",
                name: "changeContract_",
                type: "address",
            },
        ],
        name: "executeChange",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "changer_",
                type: "address",
            },
        ],
        name: "isAuthorizedChanger",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
var IGovernor__factory = /** @class */ (function () {
    function IGovernor__factory() {
    }
    IGovernor__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IGovernor__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IGovernor__factory.abi = _abi;
    return IGovernor__factory;
}());
exports.IGovernor__factory = IGovernor__factory;
//# sourceMappingURL=IGovernor__factory.js.map