"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPriceProvider__factory = exports.IMocRC20__factory = exports.IGovernor__factory = exports.IChangeContract__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IChangeContract__factory_1 = require("./IChangeContract__factory");
Object.defineProperty(exports, "IChangeContract__factory", { enumerable: true, get: function () { return IChangeContract__factory_1.IChangeContract__factory; } });
var IGovernor__factory_1 = require("./IGovernor__factory");
Object.defineProperty(exports, "IGovernor__factory", { enumerable: true, get: function () { return IGovernor__factory_1.IGovernor__factory; } });
var IMocRC20__factory_1 = require("./IMocRC20__factory");
Object.defineProperty(exports, "IMocRC20__factory", { enumerable: true, get: function () { return IMocRC20__factory_1.IMocRC20__factory; } });
var IPriceProvider__factory_1 = require("./IPriceProvider__factory");
Object.defineProperty(exports, "IPriceProvider__factory", { enumerable: true, get: function () { return IPriceProvider__factory_1.IPriceProvider__factory; } });
//# sourceMappingURL=index.js.map