"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPriceProvider__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "peek",
        outputs: [
            {
                internalType: "bytes32",
                name: "price",
                type: "bytes32",
            },
            {
                internalType: "bool",
                name: "valid",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
var IPriceProvider__factory = /** @class */ (function () {
    function IPriceProvider__factory() {
    }
    IPriceProvider__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IPriceProvider__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IPriceProvider__factory.abi = _abi;
    return IPriceProvider__factory;
}());
exports.IPriceProvider__factory = IPriceProvider__factory;
//# sourceMappingURL=IPriceProvider__factory.js.map