"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MocCAWrapper__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MocCAWrapper__factory_1 = require("./MocCAWrapper__factory");
Object.defineProperty(exports, "MocCAWrapper__factory", { enumerable: true, get: function () { return MocCAWrapper__factory_1.MocCAWrapper__factory; } });
//# sourceMappingURL=index.js.map