"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MocHelper__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "InvalidAddress",
        type: "error",
    },
    {
        inputs: [],
        name: "InvalidValue",
        type: "error",
    },
];
var MocHelper__factory = /** @class */ (function () {
    function MocHelper__factory() {
    }
    MocHelper__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    MocHelper__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    MocHelper__factory.abi = _abi;
    return MocHelper__factory;
}());
exports.MocHelper__factory = MocHelper__factory;
//# sourceMappingURL=MocHelper__factory.js.map