"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MocCARC20__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MocCARC20__factory_1 = require("./MocCARC20__factory");
Object.defineProperty(exports, "MocCARC20__factory", { enumerable: true, get: function () { return MocCARC20__factory_1.MocCARC20__factory; } });
//# sourceMappingURL=index.js.map