name: Echidna
on: [workflow_dispatch]

jobs:
  build:
    name: Run Echidna
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}       
      - run: npm ci
      - run: npm run compile
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.15
          files: .
          contract: EchidnaMocCoreTester
          crytic-args: --hardhat-ignore-compile