name: Echidna
on: [workflow_dispatch]
env:
  INFURA_API_KEY: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
  MNEMONIC: "here is where your twelve words mnemonic should be put my friend"
jobs:
  build:
    name: Run Echidna
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Compile contracts
      run: npm run compile
    - name: Run Echidna Assertion Mode
      uses: crytic/echidna-action@v2
      with:
        solc-version: 0.8.17
        files: .
        contract: EchidnaMocCoreTester
        config: contracts/echidna/default.yaml
        test-mode: assertion