name: Echidna
on: [workflow_dispatch]
env:
  INFURA_API_KEY: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
  MNEMONIC: "here is where your twelve words mnemonic should be put my friend"
jobs:
  assertion-core:
    name: Run Echidna Assertion MocCore
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Compile contracts
      run: npm run compile
    - name: Run Echidna Assertion Mode
      uses: crytic/echidna-action@v2
      with:
        solc-version: 0.8.20
        files: .
        contract: EchidnaMocCoreTester
        config: contracts/echidna/default.yaml
        test-mode: assertion
        test-limit: 20000
        crytic-args: --hardhat-ignore-compile
  property-core:
    name: Run Echidna Property MocCore
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Compile contracts
      run: npm run compile
    - name: Run Echidna Property Mode
      uses: crytic/echidna-action@v2
      with:
        solc-version: 0.8.20
        files: .
        contract: EchidnaMocCoreTester
        config: contracts/echidna/default.yaml
        test-mode: property
        test-limit: 20000
        crytic-args: --hardhat-ignore-compile
  assertion-queue:
    name: Run Echidna Assertion MocQueue
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Compile contracts
      run: npm run compile
    - name: Run Echidna Assertion Mode
      uses: crytic/echidna-action@v2
      with:
        solc-version: 0.8.18
        files: .
        contract: EchidnaMocQueueTester
        config: contracts/echidna/default.yaml
        test-mode: assertion
        test-limit: 20000
        crytic-args: --hardhat-ignore-compile